#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}


configMapGenerator:
- envs:
  - config.env
  name: vct-env

secretGenerator:
- envs:
  - secret.env
  name: vct-env-secret

resources:
- deployment.yml
- service.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: vct
  newName: ghcr.io/trustbloc/vct
  newTag: v1.0.0-rc4
