#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}

configMapGenerator:
- envs:
  - web/config.env
  name: web-env
- files:
  - web/default.conf.template
  name: nginx-config-template
- literals:
  - VOID=clear
  name: static-images
- literals:
  - VOID=clear
  name: static-icons
- literals:
  - VOID=clear
  name: static-config
- literals:
  - VOID=clear
  name: static-manifest

secretGenerator:
- envs:
  - web/secret.env
  name: web-env-secret

resources:
- web/deployment.yml
- web/service.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: wallet-web
  newName: ghcr.io/trustbloc-cicd/wallet-web
  newTag: v0.1.9-snapshot-f624081
