#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: local-kms
  newName: docker.io/nsmithuk/local-kms
  newTag: 3.11.0

configMapGenerator:
- envs:
  - config.env
  name: vcs-local-kms-env

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yml
- service.yml
