#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: v1
kind: Service
metadata:
  name: vcs-local-kms
  labels:
    app: vcs-local-kms
spec:
  ports:
    - port: 8020
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app: vcs-local-kms

